### ISSUE TITLE
Establish interface for installing libraries

### ISSUE THREAD

**Issue by SamWindell** [Floe-Project/Floe#44]
# `<name>.floe.zip` package format
```
Wraith-Floe-Package.floe.zip
│   ├ How to install.html
│   └── Libraries
│         └── Wraith
│           ├── About Wraith.html
│           ├── wraith.floe.lua
│           ├── samples
│           └── Licence.html
│   └── Presets
│       └── Wraith Factory
│           ├── About Wraith Factory Presets.html
│           ├── Pads
│           └── Textures
```
This format follows the same naming as `floe.lua` files. We want to keep it an open, standard format (zip) because it's trivial for people to access the data within. We don't want to lock things away, we want to be open. Even using the zip format but with a custom file extension would be a hurdle - it's not simple to change a file extension for someone not tech-minded.

Floe will support installing `floe.zip` files. It will read the file and understand that if it contains a Libraries subfolder, it should install it's contents to the current users libraries folder. Same goes for presets.

Users should be presented with installation instructions at the point they download the file from. However, if they do extract the zip file without consulting instructions first, they should see the How-to-install.html file will contain similar information to online. It will also contain information about manual installation.

We want to support manual installation because it's a backup option in case the automatic installation fails for whatever reason. It also is important for openness and no lock-in factors. We want people to have options and feel comfortable moving and backing up their libraries and presets. That is diminished if the only way to install things is via an automated installation process.

# Tasks

## Tweak settings GUI
- [ ] Allow for each folder to have a heading such as 'All users' and a caption for listing what libraries are in that folder. See example at bottom.
- [ ] Fetch the list of libraries in each folder and put it in the caption
- [ ] Make folder settings full width rather than having 2 columns and separate sections for library folders vs preset folders

## Modify `gen_about_lib_html_tool` into a library packaging tool
- [x] Rename tool to 'library_packager'
- [x] Generate About Library.html
- [x] Validate the lua files
- [x] Create a `.floe.zip` based on given library and presets

## Add 'add library' functionality
- [x] Add a 'add library' button to the settings panel
- [x] Make the button open a file dialog for selecting a `floe.zip`
- [ ] Add logic for extracting package files based on if they contain 'Library' or 'Presets'
- [ ] Try out Pugl WIP branch that implements drag and drop and see if works for floe.zip drops

### `How to install.html` will feature instructions for the 2 installation options:
1. Easy: use the 'add library' button or drag and drop the Wraith.floe.zip file.
2. Manual installation: extract the Wraith.floe-package.zip and copy the library and presets files manually if needed. For this function, can we make a hyperlink in the HTML that opens your library folder in your file browsers?

- [ ] Write How to install.html 
- [ ] Include friendly buttons to copy the installation folders to clipboard 
- [ ] Make the library packager tool insert it into the packages it makes

## Nice-to-have
- [ ] Add ability to automatically download and install Core library or Free libraries. Use https://docs.github.com/en/rest/releases/releases?apiVersion=2022-11-28#get-the-latest-release to get the latest release so we can check for updates too.

--- 

![Image](https://github.com/user-attachments/assets/58339d02-84cf-4a62-a79b-71a7e5592435)
